name: Sync Repo to Deployment Target

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync Repository
    if: github.repository == 'Kinghabib07/Sistem-Presensi-SAKA'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to Deployment Repo
        run: |
          git remote add target https://${{ secrets.TARGET_REPO_PAT }}@github.com/flownix-dev/Deployment-Sistem-Presensi-SAKA.git
          git push target HEAD:main --force
