name: Sync Repo to Deployment Target

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Target Repository
        env:
          TARGET_PAT: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          if [ -z "$TARGET_PAT" ]; then
            echo "ERROR: Token Rahasia 'TARGET_REPO_PAT' tidak ditemukan atau kosong! Pastikan Anda sudah membuat secret dengan nama yang BENAR."
            exit 1
          fi
          git remote add target https://flownix-dev:${TARGET_PAT}@github.com/flownix-dev/Sistem-Presensi-SAKA.git
          git push target HEAD:refs/heads/main --force
